apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hivebox
  name: hivebox
  namespace: development
spec:
  ports:
    - port: 8282
      protocol: TCP
      targetPort: 8282
  selector:
    app: hivebox
  type: ClusterIP
status:
  loadBalancer: {}
