name: tests

on:
  pull_request:
    branches: [main]
  push:
    branches: ["feat/**"]
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SENSEBOX_ID_1: ${{ vars.SENSEBOX_ID_1 }}
      SENSEBOX_ID_2: ${{ vars.SENSEBOX_ID_2 }}
      SENSEBOX_ID_3: ${{ vars.SENSEBOX_ID_3 }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Cache Go Modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Dependencies
        run: go get ./...

      - name: Cache gosec
        id: gosec-cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/gosec
          key: ${{ runner.os }}-gosec-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gosec-

      - name: Install gosec
        if: steps.gosec-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.cache/gosec
          GOBIN=~/.cache/gosec go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run gosec
        run: ~/.cache/gosec/gosec ./...

      - name: Run Tests
        run: go test ./...

      - name: Run gosec
        run: gosec ./...
