name: reusable deliver container

on:
  workflow_call:
    secrets:
      github_token:
        required: true

jobs:
  container-deliver:
    name: Deliver Container to Registry
    if: ${{github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')}}
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@8e1d5461f02b7886d3c1a774bfbd873650445aa2
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/hivebox
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@327cd5a69de6c009b9ce71bce8395f28e651bf99
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.github_token }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@e5daf5da4ebfd37300852e88eac67cc6ad147f38

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6a25f988bdfa969e96a38fc9f843ea31e0b5df27

      - name: Build and publish image
        uses: docker/build-push-action@67a2d409c0a876cbe6b11854e3e25193efe4e62d
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
