name: reusable-code-test

permissions:
  contents: read

on:
  workflow_call:

jobs:
  test-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup Go
        uses: actions/setup-go@3d10edb4c2d9ac9923e94a5ec73fa063078e9234
        with:
          go-version: "1.22"

      - name: Cache Go Modules
        uses: actions/cache@36f1e144e1c8edb0a652766b484448563d8baf46
        with:
          path: |
            ~/.cache/go-build
            /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Dependencies
        run: go get ./...

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@b12f51f7d688ab7f51c543813efbb984d466adab

      - name: Run Tests
        run: go test -v ./...

      - name: Run gosec
        run: gosec ./...

  style-go:
    name: style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup Go
        uses: actions/setup-go@3d10edb4c2d9ac9923e94a5ec73fa063078e9234
        with:
          go-version: "1.22"

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@2024.1.1
      - name: Check formatting
        run: test -z $(go fmt ./...)

      - name: Run linter
        run: staticcheck ./...
