name: reusable container test

on:
  workflow_call:

jobs:
  container-test:
    name: Build and Test Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@d292784f8f3eacda47060b259a580467b0ba410c
        with:
          dockerfile: Dockerfile

      - name: Build Docker Image For Test
        uses: docker/build-push-action@67a2d409c0a876cbe6b11854e3e25193efe4e62d
        with:
          context: .
          push: false
          tags: ${{ vars.DOCKER_USERNAME }}/hivebox:${{ github.sha }}

      - name: Test Docker container
        run: |
          docker images
          docker run --name hivebox-api -d \
          -p 8282:8282 \
          -e HIVEBOX_VERSION="0.0.1" \
          ${{ github.repository_owner }}/hivebox:${{ github.sha }}

          sleep 2

          echo Testing Image URL using wget
          wget -q -O - 127.0.0.1:8282/version | grep -i version
